apiVersion: v1
kind: Service
metadata:
  name: thrall-frontend
  namespace: thrall-defender
  labels:
    app: thrall-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: thrall-frontend
