apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thrall-defender-ingress
  namespace: thrall-defender
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd,thrall-defender-thrall-defender-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: mc-s3rv3r.ddns.net
    http:
      paths:
      # Frontend - debe ser el último para que no capture las rutas del backend
      - path: /thrall-defender
        pathType: Prefix
        backend:
          service:
            name: thrall-frontend
            port:
              number: 80
  tls:
  - hosts:
    - mc-s3rv3r.ddns.net
    secretName: thrall-defender-tls
